### ISSUE TITLE
Time is not always two digits long.

### ISSUE THREAD

**Issue by jeyemwey** [b0xCH/Traveli#2]
# Expected behavior

Time is displayed HH:MM at every place in the application, counts <10 are filled up with a leading 0.

# Actual behavior

Time is displayed h:m in Train Check-in when hour or minute count is <10.

# Steps to reproduce

Try to check-in in a train at a time <10am or during the first sixst of an hour.

# Screenshots (when needed)

![screenshot_20170307-070754](https://cloud.githubusercontent.com/assets/2796271/23644160/18d8b620-0306-11e7-9a65-2584ebaab261.png)

**Comment by b0xCH** [comment]
Thanks!
Has been fixed by using `.format('HH:mm')`! :)
![image](https://cloud.githubusercontent.com/assets/7567207/23653617/805ef8d2-032d-11e7-840b-18663123305e.png)
