### ISSUE TITLE
Proposal: Bigger destination links for trains

### ISSUE THREAD

**Issue by jeyemwey** [b0xCH/Traveli#3]
The destination links might be larger and have more padding. On small devices (e.g. Phones), changes are high to miss-click. A TableView-like design as seen at the train-chooser is in more pleasing in my eyes.

![img_-39wkhk](https://cloud.githubusercontent.com/assets/2796271/23691103/c6ca549e-03c6-11e7-92e4-078afee96c7b.jpg)

**Comment by b0xCH** [comment]
Changed the padding between the destination stations. Should be easier to select the right entry now! :)
